site_name: Meus Documentos
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'cloud'
  language: 'pt'
extra:
  search:
    language: 'en, pt'
feature:
    tabs: true
repo_name :  'Michael Douglas' 
repo_url :  'https://github.com/mchdouglas'
copyright: "Michael Douglas 2020 &copy; todos os direiros reservados"
extra:
  social:
    - type: 'github'
      link: 'https://github.com/mchdouglas'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/michael-douglas-b1125619b/'
