site_name: Meus Documentos
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'amber'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
#   logo:
    logo: 'cloud'
  language: 'pt'
extra:
  search:
    language: 'en, pt'
feature:
    tabs: true
repo_name :  'Michael Douglas' 
repo_url :  'https://github.com/mchdouglas'
copyright: "Michael Douglas 2020 &copy; todos os direiros reservados"